### PR TITLE
adapted to use `OSCFunc` rather than deprecated `OSCresponder`

### PR DESCRIPTION
**Pull request by LFSaw**

### CODE REVIEW

**Review by nhthn — APPROVED** [review]

**Review by adcxyz — APPROVED** [review]
looks good! it mixes the change to OSCFunc with cosmetics, but only a few lines, so not a problem.

**Comment by adcxyz** [comment]
thanks till!

**Comment by LFSaw** [comment]
> it mixes the change to OSCFunc with cosmetics, but only a few lines, so not a problem.

this is really interesting and caused by `select-all + <tab>` in the IDE...

**Comment by adcxyz** [comment]
yes, it is automatic cleanup as a side-effect - which is fine with me 
as long as it does not obscure the relevant changes ;-)

**Comment by LFSaw** [comment]
prrfct :)

**Pull request merged**
